-- order-service schema. Matches com.ecommerce.orderservice.entity.OrderEntity + OrderLine.
CREATE TABLE orders (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     VARCHAR(255) NOT NULL,
    status      VARCHAR(255) NOT NULL,
    total_cents BIGINT NOT NULL,
    payment_id  BIGINT,
    created_at  TIMESTAMP(6) WITH TIME ZONE NOT NULL
);

CREATE TABLE order_lines (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id         BIGINT REFERENCES orders (id),
    product_id       BIGINT NOT NULL,
    quantity         INTEGER NOT NULL,
    unit_price_cents BIGINT NOT NULL
);

CREATE INDEX idx_orders_user_id ON orders (user_id);
CREATE INDEX idx_order_lines_order_id ON order_lines (order_id);
